[versions]
# Build tools
agp = "9.0.0"
lsparanoid = "0.6.0"
autoService = "1.1.1"

# AndroidX
annotation = "1.9.1"
constraintlayout = "2.2.1"
coordinatorlayout = "1.3.0"
core = "1.17.0"
fragment = "1.8.9"
recyclerview = "1.4.0"

# UI Libraries
miuix = "1.0.10.5.1"

# Xposed & Hooks
xposed-api = "100-1.0.3"
dexkit = "2.0.7"
ezxhelper = "3.1.1-rc1"
hiddenapibypass = "6.1"

# Third-party
expansions = "1.0.0"
gson = "2.13.2"
hyperfocusapi = "2.0"
lunarcalendar = "latest.release"
superLyricApi = "2.4"

[libraries]
# AndroidX
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
core = { module = "androidx.core:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

# Miuix UI
miuix-animation = { module = "fan.miuix:animation", version.ref = "miuix" }
miuix-appcompat = { module = "fan.miuix:appcompat", version.ref = "miuix" }
miuix-basewidget = { module = "fan.miuix:basewidget", version.ref = "miuix" }
miuix-bottomsheet = { module = "fan.miuix:bottomsheet", version.ref = "miuix" }
miuix-cardview = { module = "fan.miuix:cardview", version.ref = "miuix" }
miuix-core = { module = "fan.miuix:core", version.ref = "miuix" }
miuix-flexible = { module = "fan.miuix:flexible", version.ref = "miuix" }
miuix-folme = { module = "fan.miuix:folme", version.ref = "miuix" }
miuix-graphics = { module = "fan.miuix:graphics", version.ref = "miuix" }
miuix-haptic = { module = "fan.miuix:haptic", version.ref = "miuix" }
miuix-mgl = { module = "fan.miuix:mgl", version.ref = "miuix" }
miuix-navigator = { module = "fan.miuix:navigator", version.ref = "miuix" }
miuix-nestedheader = { module = "fan.miuix:nestedheader", version.ref = "miuix" }
miuix-pickerwidget = { module = "fan.miuix:pickerwidget", version.ref = "miuix" }
miuix-popupwidget = { module = "fan.miuix:popupwidget", version.ref = "miuix" }
miuix-preference = { module = "fan.miuix:preference", version.ref = "miuix" }
miuix-recyclerview = { module = "fan.miuix:recyclerview", version.ref = "miuix" }
miuix-slidingwidget = { module = "fan.miuix:slidingwidget", version.ref = "miuix" }
miuix-smooth = { module = "fan.miuix:smooth", version.ref = "miuix" }
miuix-springback = { module = "fan.miuix:springback", version.ref = "miuix" }
miuix-stretchablewidget = { module = "fan.miuix:stretchablewidget", version.ref = "miuix" }
miuix-theme = { module = "fan.miuix:theme", version.ref = "miuix" }
miuix-viewpager = { module = "fan.miuix:viewpager", version.ref = "miuix" }
miuix-visualcheck = { module = "fan.miuix:visualcheck", version.ref = "miuix" }

# Xposed & Hooks
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
ezxhelper-android-utils = { module = "io.github.kyuubiran.ezxhelper:android-utils", version.ref = "ezxhelper" }
ezxhelper-core = { module = "io.github.kyuubiran.ezxhelper:core", version.ref = "ezxhelper" }
ezxhelper-xposed-api = { module = "io.github.kyuubiran.ezxhelper:xposed-api-100", version.ref = "ezxhelper" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
libxposed-api = { module = "io.github.libxposed:api", version.ref = "xposed-api" }
libxposed-service = { module = "io.github.libxposed:service", version.ref = "xposed-api" }

# Third-party
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
expansion = { module = "com.sevtinge.hyperceiler:hyperceiler-expansion", version.ref = "expansions" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hyperfocusapi = { module = "com.github.ghhccghk:HyperFocusApi", version.ref = "hyperfocusapi" }
lunarcalendar = { module = "com.xhinliang:LunarCalendar", version.ref = "lunarcalendar" }
superlyricapi = { module = "com.github.HChenX:SuperLyricApi", version.ref = "superLyricApi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
lsparanoid = { id = "org.lsposed.lsparanoid", version.ref = "lsparanoid" }

[bundles]
miuix = [
    "miuix-animation", "miuix-appcompat", "miuix-basewidget", "miuix-bottomsheet",
    "miuix-cardview", "miuix-core", "miuix-flexible", "miuix-folme", "miuix-graphics",
    "miuix-haptic", "miuix-mgl", "miuix-navigator", "miuix-nestedheader",
    "miuix-pickerwidget", "miuix-popupwidget", "miuix-preference", "miuix-recyclerview",
    "miuix-slidingwidget", "miuix-smooth", "miuix-springback", "miuix-stretchablewidget",
    "miuix-theme", "miuix-viewpager", "miuix-visualcheck"
]
ezxhelper = ["ezxhelper-core", "ezxhelper-xposed-api", "ezxhelper-android-utils"]
