[versions]
agp = "8.8.0"
kotlin-android = "2.1.10"
lsparanoid = "0.6.0"
autoService = "1.1.1"

annotation = "1.9.1"
core = "1.15.0"
fragment = "1.8.5"
lunarcalendar = "latest.release"
recyclerview = "1.4.0"
coordinatorlayout = "1.2.0"
constraintlayout = "2.2.0"

xposed-api = "82"

gson = "2.11.0"
dexkit = "2.0.3"
ezxhelper = "2.2.0"
hiddenapibypass = "6.0"
hooktool = "v.1.2.0"
lyricGetterApi = "6.0.0"
mmkv = "2.0.2"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
hooktool = { module = "com.github.HChenX:HookTool", version.ref = "hooktool" }
lunarcalendar = { module = "com.xhinliang:LunarCalendar", version.ref = "lunarcalendar" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

auto-service = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed-api" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
dexkit = { group = "org.luckypray", name = "dexkit", version.ref = "dexkit" }
ezxhelper = { group = "com.github.kyuubiran", name = "EzXHelper", version.ref = "ezxhelper" }
hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "hiddenapibypass" }
lyric-getter-api = { module = "com.github.xiaowine:Lyric-Getter-Api", version.ref = "lyricGetterApi" }
mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
lsparanoid = { id = "org.lsposed.lsparanoid", version.ref = "lsparanoid" }

[bundles]

